Request for code review
MauricioRobayo/re-former pull request #1
Opened 2019-09-12 21:45 UTC by MauricioRobayo

2019-09-15 04:12 UTC, adriaanbd requested changes
We are missing the commented out `form_tag` that is required as a step prior to the `form_for`. Furthermore, if you follow GitFlow guidelines [here](https://github.com/microverseinc/linters-config/tree/master/ruby) properly, we shouldn't have any code on master branch until your first release is approved (this PR) to be merged *from feature branch to develop branch*.

Also, to avoid repeating the same code in `new.html.erb` and `edit.html.erb`, you can use a partial `_foobar.html.erb`.

See my comments below.

Status: `Request changes`

2019-09-15 04:12 UTC, adriaanbd commented on app/models/user.rb
> +class User < ApplicationRecord
Might want to validate uniqueness of username and email to prevent two or more users having the same email or username

[OPTIONAL]

2019-09-15 04:12 UTC, adriaanbd commented on app/views/users/edit.html.erb
> +<%= form_for @user, url: user_path(@user) do |usr| %>
Missing the commented out `form_tag` that was required prior to this. Commented out code is normally requested to be removed from the repo according to the guidelines but this project in particular requires this one to have that as commented out code.

[REQUIRED]

2019-09-15 04:12 UTC, adriaanbd commented on app/views/users/new.html.erb
> +<%= form_for @user do |usr| %>
See the above comment on `form_tag`

[REQUIRED]

2019-09-15 04:12 UTC, adriaanbd commented on test/controllers/users_controller_test.rb
> +class UsersControllerTest < ActionDispatch::IntegrationTest
Delete unused test files. Next time you can start a new Rails app without the default testing framework by using the `-T` flag `$rails new app -T`

[OPTIONAL]

2019-09-15 04:12 UTC, adriaanbd commented on test/fixtures/users.yml
> +one:
Delete unused test files. Next time you can start a new Rails app without the default testing framework by using the `-T` flag `$rails new app -T`

[OPTIONAL]

2019-09-15 04:12 UTC, adriaanbd commented on test/models/user_test.rb
> +class UserTest < ActiveSupport::TestCase
Delete unused test files. Next time you can start a new Rails app without the default testing framework by using the `-T` flag `$rails new app -T`

[OPTIONAL]

2019-09-16 15:39 UTC, closed without merging

2019-09-16 17:09 UTC, MauricioRobayo commented
@adriaanbd We were trying to clean the development and master branches so there were no commits on those, but while doing that Github closed this pull request and we are not able to open it again. So we opened a new pull request with all the issues you pointed out fixed: #2.

Thanks!

2019-09-17 05:36 UTC, adriaanbd commented
Hey, we all have Git issues, don't worry!